"""Add BlogPostSection model

Revision ID: 28330d72385b
Revises: 
Create Date: 2024-09-07 21:50:54.027425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28330d72385b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('output')
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.TEXT(), nullable=True))

    op.drop_table('blog_post_section')
    # ### end Alembic commands ###
